In [45]:
# This Python 3 environment comes with many helpful analytics libraries installed
# It is defined by the kaggle/python docker image: https://github.com/kaggle/docker-python
# For example, here's several helpful packages to load in 

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

# Input data files are available in the "../input/" directory.
# For example, running this (by clicking run or pressing Shift+Enter) will list all files under the input directory

import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

# Any results you write to the current directory are saved as output.

/kaggle/input/pima-indians-diabetes-database/diabetes.csv


In [46]:
!pip install pyswarms

In [47]:
import tensorflow as tf
from tensorflow import keras
from keras.models import Sequential
from keras.layers import Dense
import csv 
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import pickle
import random
from keras.layers import Concatenate, concatenate
from keras.layers.normalization import BatchNormalization
import numpy as np
import h5py
from sklearn.metrics import accuracy_score
from sklearn.utils import shuffle
from sklearn.model_selection import train_test_split
import pyswarms as ps


In [48]:
import pandas as pd
pima_indians_diabetes = pd.read_csv("../input/pima-indians-diabetes-database/diabetes.csv")
pima_indians_diabetes = shuffle(pima_indians_diabetes);

In [49]:
print(pima_indians_diabetes.head(10))

     Pregnancies  Glucose  BloodPressure  SkinThickness  Insulin   BMI  \
318            3      115             66             39      140  38.1   
592            3      132             80              0        0  34.4   
675            6      195             70              0        0  30.9   
233            4      122             68              0        0  35.0   
582           12      121             78             17        0  26.5   
630            7      114             64              0        0  27.4   
412            1      143             84             23      310  42.4   
635           13      104             72              0        0  31.2   
451            2      134             70              0        0  28.9   
171            6      134             70             23      130  35.4   

     DiabetesPedigreeFunction  Age  Outcome  
318                     0.150   28        0  
592                     0.402   44        1  
675                     0.328   31        1  
2

In [50]:
dataset = pima_indians_diabetes.values

In [51]:
dataset

array([[3.00e+00, 1.15e+02, 6.60e+01, ..., 1.50e-01, 2.80e+01, 0.00e+00],
       [3.00e+00, 1.32e+02, 8.00e+01, ..., 4.02e-01, 4.40e+01, 1.00e+00],
       [6.00e+00, 1.95e+02, 7.00e+01, ..., 3.28e-01, 3.10e+01, 1.00e+00],
       ...,
       [0.00e+00, 1.11e+02, 6.50e+01, ..., 6.60e-01, 3.10e+01, 0.00e+00],
       [8.00e+00, 1.33e+02, 7.20e+01, ..., 2.70e-01, 3.90e+01, 1.00e+00],
       [3.00e+00, 1.22e+02, 7.80e+01, ..., 2.54e-01, 4.00e+01, 0.00e+00]])

In [52]:

X = dataset[:,0:8]
Y = dataset[:,8]

In [53]:
X

array([[3.00e+00, 1.15e+02, 6.60e+01, ..., 3.81e+01, 1.50e-01, 2.80e+01],
       [3.00e+00, 1.32e+02, 8.00e+01, ..., 3.44e+01, 4.02e-01, 4.40e+01],
       [6.00e+00, 1.95e+02, 7.00e+01, ..., 3.09e+01, 3.28e-01, 3.10e+01],
       ...,
       [0.00e+00, 1.11e+02, 6.50e+01, ..., 2.46e+01, 6.60e-01, 3.10e+01],
       [8.00e+00, 1.33e+02, 7.20e+01, ..., 3.29e+01, 2.70e-01, 3.90e+01],
       [3.00e+00, 1.22e+02, 7.80e+01, ..., 2.30e+01, 2.54e-01, 4.00e+01]])

In [54]:
Y

array([0., 1., 1., 0., 0., 1., 0., 1., 1., 1., 0., 1., 0., 0., 1., 0., 1.,
       1., 0., 1., 0., 1., 0., 0., 0., 0., 0., 1., 0., 1., 1., 1., 0., 0.,
       0., 0., 1., 0., 1., 0., 0., 0., 0., 0., 1., 1., 1., 0., 0., 0., 0.,
       0., 0., 0., 0., 1., 1., 1., 1., 0., 0., 0., 0., 1., 1., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 1., 1., 0., 1., 1., 0., 0., 0., 1., 0., 1.,
       0., 0., 0., 1., 1., 0., 1., 0., 0., 1., 0., 0., 1., 0., 0., 1., 1.,
       0., 1., 1., 1., 0., 1., 0., 0., 1., 0., 1., 0., 0., 0., 0., 0., 0.,
       1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0.,
       0., 1., 0., 1., 0., 0., 0., 1., 0., 0., 0., 1., 0., 0., 0., 0., 1.,
       0., 0., 1., 1., 0., 0., 0., 0., 1., 0., 0., 0., 0., 1., 0., 0., 1.,
       0., 1., 1., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 1., 0., 0., 0.,
       0., 1., 1., 0., 1., 1., 1., 1., 1., 1., 0., 0., 1., 0., 0., 1., 0.,
       1., 1., 1., 1., 1., 1., 0., 0., 1., 0., 0., 0., 0., 0., 0., 1., 1.,
       0., 1., 1., 0., 0.

In [55]:
X_train, X_test, y_train, y_test = train_test_split(X, Y)

In [56]:
y_train = y_train.astype(int)

In [57]:
y_train

array([1, 1, 1, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0,
       1, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 1, 1, 1, 0, 1, 1, 1,
       0, 1, 0, 0, 1, 1, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0, 1, 1, 0,
       0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 1, 0, 1, 1, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1,
       0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 1, 0, 0,
       0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 1, 0, 1, 0, 1, 1, 0, 0, 0, 0, 1, 1,
       1, 1, 1, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 1, 1, 1, 0,
       0, 0, 1, 0, 1, 0, 0, 1, 1, 0, 0, 1, 1, 1, 1, 1, 0, 1, 0, 0, 1, 1,
       1, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 1,
       0, 1, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 1, 1, 1, 1, 1,
       0, 0, 1, 1, 1, 0, 0, 0, 1, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 0,
       1, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1, 1, 0, 1, 0, 0,
       0, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0, 1, 1, 1, 1,

In [70]:
model = Sequential()
model.add(Dense(16, activation='sigmoid', input_shape=(8,)))
model.add(Dense(2, activation='sigmoid'))
model.summary()

Model: "sequential_1005"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense_2009 (Dense)           (None, 16)                144       
_________________________________________________________________
dense_2010 (Dense)           (None, 2)                 34        
Total params: 178
Trainable params: 178
Non-trainable params: 0
_________________________________________________________________


In [71]:
from sklearn.metrics import mean_squared_error
from sklearn.metrics import confusion_matrix
from sklearn.metrics import accuracy_score
from sklearn.metrics import average_precision_score

In [72]:
print(y_train.shape)

(576,)


In [76]:
# Forward propagation
def forward_prop(params):
    # Neural network architecture
    n_inputs = 8
    n_hidden = 16
    n_classes = 2
    #print("1")
  
    # Roll-back the weights and biases
    W1 = params[0:128].reshape((n_inputs,n_hidden))
    b1 = params[128:144].reshape((n_hidden,))
    W2 = params[144:176].reshape((n_hidden,n_classes))
    b2 = params[176:178].reshape((n_classes,))
    
    # Perform forward propagation
    z1 = X_train.dot(W1) + b1  # Pre-activation in Layer 1
    a1 = np.tanh(z1)     # Activation in Layer 1
    z2 = a1.dot(W2) + b2 # Pre-activation in Layer 2
    logits = z2          # Logits for Layer 2

    # Compute for the softmax of the logits
    exp_scores = np.exp(logits)
    probs = exp_scores / np.sum(exp_scores, axis=1, keepdims=True)
    # Compute for the negative log likelihood
    N = 576 # Number of samples
    corect_logprobs = -np.log(probs[range(N), y_train])
    loss = np.sum(corect_logprobs) / N

    return loss

In [77]:
def f(x):
    n_particles = x.shape[0]
    #print(x[1])
    j = [forward_prop(x[i]) for i in range(n_particles)]
    return np.array(j)

In [86]:
# Initialize swarm
options = {'c1': 0.5, 'c2': 0.3, 'w':0.9}

# Call instance of PSO
dimensions = (8 * 16) + (16 * 2) + 16 + 2
optimizer = ps.single.GlobalBestPSO(n_particles=100, dimensions=dimensions, options=options)

# Perform optimization
cost, pos = optimizer.optimize(f, iters=100)

2020-03-10 18:09:47,931 - pyswarms.single.global_best - INFO - Optimize for 50 iters with {'c1': 0.5, 'c2': 0.3, 'w': 0.9}





pyswarms.single.global_best:   0%|          |0/50




pyswarms.single.global_best:   0%|          |0/50, best_cost=0.655




pyswarms.single.global_best:   0%|          |0/50, best_cost=0.655




pyswarms.single.global_best:   4%|▍         |2/50, best_cost=0.655




pyswarms.single.global_best:   4%|▍         |2/50, best_cost=0.655




pyswarms.single.global_best:   4%|▍         |2/50, best_cost=0.655




pyswarms.single.global_best:   8%|▊         |4/50, best_cost=0.655




pyswarms.single.global_best:   8%|▊         |4/50, best_cost=0.655




pyswarms.single.global_best:   8%|▊         |4/50, best_cost=0.655




pyswarms.single.global_best:  12%|█▏        |6/50, best_cost=0.655




pyswarms.single.global_best:  12%|█▏        |6/50, best_cost=0.655




pyswarms.single.global_best:  12%|█▏        |6/50, best_cost=0.655




pyswarms.single.global_best:  16%|█▌ 

In [87]:
from sklearn.metrics import accuracy_score
def predict(X, pos):
    """
    Use the trained weights to perform class predictions.
    Inputs
    ------
    X: numpy.ndarray
        Input Iris dataset
    pos: numpy.ndarray
        Position matrix found by the swarm. Will be rolled
        into weights and biases.
    """
     # Neural network architecture
    n_inputs = 8
    n_hidden = 16
    n_classes = 2
    #print("1")
  
    # Roll-back the weights and biases
    W1 = pos[0:128].reshape((n_inputs,n_hidden))
    b1 = pos[128:144].reshape((n_hidden,))
    W2 = pos[144:176].reshape((n_hidden,n_classes))
    b2 = pos[172:174].reshape((n_classes,))
    
    # Perform forward propagation
    z1 = X.dot(W1) + b1  # Pre-activation in Layer 1
    a1 = np.tanh(z1)     # Activation in Layer 1
    z2 = a1.dot(W2) + b2 # Pre-activation in Layer 2
    logits = z2          # Logits for Layer 2

    y_pred = np.argmax(logits, axis=1)
    return y_pred

    

In [88]:
print("Prediction accuracy :",str((predict(X_test,pos) == y_test).mean()))

Prediction accuracy : 0.6875
