In [88]:
# This Python 3 environment comes with many helpful analytics libraries installed
# It is defined by the kaggle/python docker image: https://github.com/kaggle/docker-python
# For example, here's several helpful packages to load in 

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

# Input data files are available in the "../input/" directory.
# For example, running this (by clicking run or pressing Shift+Enter) will list all files under the input directory

import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

# Any results you write to the current directory are saved as output.

/kaggle/input/bankmarketing/bank marketing.csv


In [89]:
!pip install pyswarms

In [90]:
import tensorflow as tf
from tensorflow import keras
from keras.models import Sequential
from keras.layers import Dense
import csv 
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import pickle
import random
from keras.layers import Concatenate, concatenate
from keras.layers.normalization import BatchNormalization
import numpy as np
import h5py
from sklearn.metrics import accuracy_score
from sklearn.utils import shuffle
from sklearn.model_selection import train_test_split
import pyswarms as ps


In [91]:
import pandas as pd
df = pd.read_csv("../input/bankmarketing/bank marketing.csv")
df = shuffle(df);
list(df.columns)

['age',
 'job',
 'marital',
 'education',
 'default',
 'balance',
 'housing',
 'loan',
 'contact',
 'day',
 'month',
 'duration',
 'campaign',
 'pdays',
 'previous',
 'poutcome',
 'market?']

In [92]:
df.drop(['job', 'marital','education','contact','month','poutcome'], axis = 1, inplace=True) 

In [93]:
dataset = df.values

In [94]:
dataset

array([[  36,    0,    6, ...,   -1,    0,    0],
       [  41,    0,  231, ...,   -1,    0,    1],
       [  39,    0, 5803, ...,   -1,    0,    0],
       ...,
       [  34,    0,  475, ...,   -1,    0,    0],
       [  34,    0,    0, ...,   -1,    0,    0],
       [  60,    0,  322, ...,   -1,    0,    0]])

In [95]:

X = dataset[:,0:10]
Y = dataset[:,10]

In [96]:
X

array([[  36,    0,    6, ...,    7,   -1,    0],
       [  41,    0,  231, ...,    2,   -1,    0],
       [  39,    0, 5803, ...,    3,   -1,    0],
       ...,
       [  34,    0,  475, ...,    1,   -1,    0],
       [  34,    0,    0, ...,    2,   -1,    0],
       [  60,    0,  322, ...,    1,   -1,    0]])

In [97]:
Y

array([0, 1, 0, ..., 0, 0, 0])

In [98]:
X_train, X_test, y_train, y_test = train_test_split(X, Y)

In [99]:
y_train = y_train.astype(int)

In [100]:
y_train

array([0, 0, 0, ..., 0, 0, 0])

In [101]:
model = Sequential()
model.add(Dense(20, activation='sigmoid', input_shape=(10,)))
model.add(Dense(2, activation='sigmoid'))
model.summary()

Model: "sequential_3"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense_5 (Dense)              (None, 20)                220       
_________________________________________________________________
dense_6 (Dense)              (None, 2)                 42        
Total params: 262
Trainable params: 262
Non-trainable params: 0
_________________________________________________________________


In [102]:
from sklearn.metrics import mean_squared_error
from sklearn.metrics import confusion_matrix
from sklearn.metrics import accuracy_score
from sklearn.metrics import average_precision_score

In [103]:
print(y_train.shape)

(3390,)


In [104]:
# Forward propagation
def forward_prop(params):
    # Neural network architecture
    n_inputs = 10
    n_hidden = 20
    n_classes = 2
    #print("1")
  
    # Roll-back the weights and biases
    W1 = params[0:200].reshape((n_inputs,n_hidden))
    b1 = params[200:220].reshape((n_hidden,))
    W2 = params[220:260].reshape((n_hidden,n_classes))
    b2 = params[260:262].reshape((n_classes,))
    
    # Perform forward propagation
    z1 = X_train.dot(W1) + b1  # Pre-activation in Layer 1
    a1 = np.tanh(z1)     # Activation in Layer 1
    z2 = a1.dot(W2) + b2 # Pre-activation in Layer 2
    logits = z2          # Logits for Layer 2

    # Compute for the softmax of the logits
    exp_scores = np.exp(logits)
    probs = exp_scores / np.sum(exp_scores, axis=1, keepdims=True)
    # Compute for the negative log likelihood
    N = 3390 # Number of samples
    corect_logprobs = -np.log(probs[range(N), y_train])
    loss = np.sum(corect_logprobs) / N

    return loss

In [105]:
def f(x):
    n_particles = x.shape[0]
    #print(x[1])
    j = [forward_prop(x[i]) for i in range(n_particles)]
    return np.array(j)

In [106]:
# Initialize swarm
options = {'c1': 0.5, 'c2': 0.3, 'w':0.9}

# Call instance of PSO
dimensions = (10 * 20) + (20 * 2) + 20 + 2
optimizer = ps.single.GlobalBestPSO(n_particles=35, dimensions=dimensions, options=options)

# Perform optimization
cost, pos = optimizer.optimize(f, iters=35)

2020-03-10 20:24:50,000 - pyswarms.single.global_best - INFO - Optimize for 35 iters with {'c1': 0.5, 'c2': 0.3, 'w': 0.9}




pyswarms.single.global_best:   0%|          |0/35



pyswarms.single.global_best:   0%|          |0/35, best_cost=0.365



pyswarms.single.global_best:   3%|▎         |1/35, best_cost=0.365



pyswarms.single.global_best:   3%|▎         |1/35, best_cost=0.365



pyswarms.single.global_best:   6%|▌         |2/35, best_cost=0.365



pyswarms.single.global_best:   6%|▌         |2/35, best_cost=0.365



pyswarms.single.global_best:   9%|▊         |3/35, best_cost=0.365



pyswarms.single.global_best:   9%|▊         |3/35, best_cost=0.365



pyswarms.single.global_best:  11%|█▏        |4/35, best_cost=0.365



pyswarms.single.global_best:  11%|█▏        |4/35, best_cost=0.365



pyswarms.single.global_best:  14%|█▍        |5/35, best_cost=0.365



pyswarms.single.global_best:  14%|█▍        |5/35, best_cost=0.365



pyswarms.single.global_best:  17%|█▋        |6/35,

In [107]:
from sklearn.metrics import accuracy_score
def predict(X, pos):
    """
    Use the trained weights to perform class predictions.
    Inputs
    ------
    X: numpy.ndarray
        Input Iris dataset
    pos: numpy.ndarray
        Position matrix found by the swarm. Will be rolled
        into weights and biases.
    """
     # Neural network architecture
    n_inputs = 10
    n_hidden = 20
    n_classes = 2
    #print("1")
  
    # Roll-back the weights and biases
    W1 = pos[0:200].reshape((n_inputs,n_hidden))
    b1 = pos[200:220].reshape((n_hidden,))
    W2 = pos[220:260].reshape((n_hidden,n_classes))
    b2 = pos[260:262].reshape((n_classes,))
    
    # Perform forward propagation
    z1 = X.dot(W1) + b1  # Pre-activation in Layer 1
    a1 = np.tanh(z1)     # Activation in Layer 1
    z2 = a1.dot(W2) + b2 # Pre-activation in Layer 2
    logits = z2          # Logits for Layer 2

    y_pred = np.argmax(logits, axis=1)
    return y_pred

    

In [108]:
print("Prediction accuracy :",str((predict(X_test,pos) == y_test).mean()))

Prediction accuracy : 0.8806366047745358
